---
- name: Add RabbitMQ Apt Repository
  apt_repository:
    repo: deb http://www.rabbitmq.com/debian/ testing main
    state: present
    filename: 'rabbitmq'

- apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present

- name: Update repositories cache and install "rabbitmq-server" package
  apt:
    name: rabbitmq-server
    update_cache: yes
    state: present
  

