---
dependencies:
  - role: gantsign.visual-studio-code
    users:
        - username: lnunno
          visual_studio_code_extensions:
            - ms-vscode.cpptools
            - robertohuertasm.vscode-icons
            - lukehoban.Go
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - donjayamanne.python
          visual_studio_code_settings: {
            "editor.rulers": [120],
            "editor.fontSize": 16,
            "files.associations": {
              "Vagrantfile": "ruby",
              "*.jsonschema": "json"
            }
          }