- name: Ensure build tools are available.
  apt: name={{ item }} state=latest
  with_items:
        - build-essential
        - vim
        - git
        - zsh
        - tmux
- git_config:
    name: core.editor
    value: vim
    scope: global
- git_config:
    name: push.default
    value: simple
    scope: global
- git_config:
    name: user.name
    value: Lucas Nunno
    scope: global
- git_config:
    name: user.email
    value: lucasnunno@gmail.com
    scope: global