# Git aliases
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gs="git status"
alias gu="git pull"
alias gp="git push"
alias gl="git log"
alias gc="git commit"
alias gco="git checkout"
alias gr="git rebase"
alias gm="git merge"
