---
dependencies:
  # - role: alban.andrieu.eclipse
  # - role: dotstrap.fzf
  # Installs Eclipse.
  # - role: caarlos0.eclipse
  # Installs Visual Studio Code.
  - role: gantsign.visual-studio-code
    users:
        - username: lnunno
          visual_studio_code_extensions:
            - ms-vscode.cpptools
            # - robertohuertasm.vscode-icons
            - lukehoban.Go
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - donjayamanne.python
          visual_studio_code_settings: {
            "editor.rulers": [120],
            "editor.fontSize": 16,
            "editor.tabSize": 4,
            "editor.insertSpaces": true,
            "editor.detectIndentation": false,
            "extensions.autoUpdate": true,
            "files.associations": {
              "Vagrantfile": "ruby",
              "*.jsonschema": "json"
            }
          }